### ISSUE TITLE
Testcases fail

### ISSUE THREAD

**Issue by mabbamOG** [viperproject/prusti-dev#337] opened 2021-01-03 16:24 UTC
on the latest master, on MacOS BigSur, the `cargo test` command fails.
the output is attached.

[log.txt](https://github.com/viperproject/prusti-dev/files/5761866/log.txt)

**Comment by mabbamOG** [comment] 2021-01-03 16:40
after compiling the project in debug mode (with `cargo build`), the testcases proceeded. Apparently `cargo test` expects the user to have manually compiled the program in debug-mode before-hand? I was under the impression that cargo did that automatically...has this been disabled?

Anyway, the testcases still fail, the output is attached.
[log.txt](https://github.com/viperproject/prusti-dev/files/5761893/log.txt)

**Comment by vakaras** [comment] 2021-01-03 16:44
It seems that Prusti fails to read NLL facts. Is `prusti-tests/nll-facts/` present on your system? Also, what is the active toolchain (shown by `rustup show`)?

**Comment by mabbamOG** [comment] 2021-01-03 16:52
there is no directory `prusti-tests/nll-facts` on the master branch of this repository, which is what i cloned:

```
➜  prusti-dev git:(master) fd nll                        
prusti-tests/tests/verify/fail/nll-rfc
prusti-tests/tests/verify/pass/nll-rfc
prusti-tests/tests/verify/pass/quick/nll-rfc-case1.rs
prusti-tests/tests/verify_overflow/pass/nll-rfc
prusti-tests/tests_old/verify_overflow/pass/nll-rfc
```

the active toolchain seems to be `nightly-2020-12-15-x86_64-apple-darwin`. if this chage was performed by prusti, i might add that i do not particularly appreciate any program implicitly modifying such default configurations on my system, especially when i use rust to build other projects than prusti.

```
➜  prusti-dev git:(master) rustup show                                  
Default host: x86_64-apple-darwin
rustup home:  /Users/user/.rustup

installed toolchains
--------------------

stable-x86_64-apple-darwin (default)
nightly-2018-06-27-x86_64-apple-darwin
nightly-2020-12-15-x86_64-apple-darwin
nightly-x86_64-apple-darwin

active toolchain
----------------

nightly-2020-12-15-x86_64-apple-darwin (overridden by '/Users/user/Downloads/TMP/prusti-dev/rust-toolchain')
rustc 1.50.0-nightly (fa4163942 2020-12-14)
```

**Comment by vakaras** [comment] 2021-01-03 17:06
> there is no directory `prusti-tests/nll-facts` on the master branch of this repository, which is what i cloned:

It should be generated when running tests. If it does not get generated, we should figure out why. (Prusti extracts some of the information it needs form the compiler log files. That is super ugly, but there does not seem to be an alternative until the compiler gets refactored into reusable components.)

> if this chage was performed by prusti

It is set by `rust-toolchain` file in the repository. This is [the standard way](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file) of setting a specific version of the compiler for projects that depend on the compiler internals. The `rust-toolchain` file sets the toolchain version only for that directory.

**Comment by mabbamOG** [comment] 2021-01-03 18:16
As noted in #336, my build was probably botched. All the tests now run fine.

> It should be generated when running tests. If it does not get generated, we should figure out why

unfortunately, the folder is still missing: 

```bash
➜  prusti-dev2 git:(master) fd nll
prusti-tests/tests/verify/fail/nll-rfc
prusti-tests/tests/verify/pass/nll-rfc
prusti-tests/tests/verify/pass/quick/nll-rfc-case1.rs
prusti-tests/tests/verify_overflow/pass/nll-rfc
prusti-tests/tests_old/verify_overflow/pass/nll-rfc
```

> It is set by rust-toolchain file in the repository. This is the standard way ...

got it, thanks for the clarification! as i mentioned, i only took issue to this if it did indeed modify my default system configuration 😄 

i might add that i started to have all these issues after i switched to prusti-dev because prusti-assistant was broken on my system... perhaps someone can look into that as well?

thanks for the support!

**Comment by vakaras** [comment] 2021-01-03 18:31
> i might add that i started to have all these issues after i switched to prusti-dev because prusti-assistant was broken on my system... perhaps someone can look into that as well?

@fpoli Any suggestions on how to investigate this? You can find the problem description on [Zulip](https://prusti.zulipchat.com/#narrow/stream/236614-general/topic/prusti-assistant.20error.3F).

**Comment by fpoli** [comment] 2021-01-04 09:22
> Apparently cargo test expects the user to have manually compiled the program in debug-mode before-hand? I was under the impression that cargo did that automatically...has this been disabled?

Cargo doesn't do that, because `cargo test` depends on one *binary file* generated by `cargo debug`, not on a Rust library. The issue is #226. We have found no better way to specify that dependency so far.

**Comment by fpoli** [comment] 2021-01-04 10:01
Regarding the `nll-facts` folder, I recently moved it inside the `log` folder: `prusti-tests/log/nll-facts/`.

> @fpoli Any suggestions on how to investigate this? You can find the problem description on Zulip.

I suspect that the `rustup` version might have broken something in the first installation. You could try to uninstall the extension, restart the IDE, and install it again. As mentioned in https://github.com/viperproject/prusti-assistant/issues/25, I would need to see the log messages of the extension.

**Comment by fpoli** [comment] 2021-01-06 14:26
> All the tests now run fine.

Closing

**Closed as completed by fpoli** 2021-01-06 14:26 UTC
