### ISSUE TITLE
Getting the external crates

### ISSUE THREAD

**Issue by trj2059** [viperproject/prusti-dev#140] opened 2020-08-31 00:49 UTC
The verifier works fine when installing from the VSCode, however I can't seem to find instructions on getting the external crates so you can compile with the annotations.   Are there instructions somewhere in the codebase?

**Comment by vakaras** [comment] 2020-08-31 21:28
This is not supported yet. @karenhong maybe could tell more about the status of this feature.

**Comment by fpoli** [comment] 2020-09-01 08:04
Related: #2

**Comment by fpoli** [comment] 2020-09-01 11:08
> getting the external crates

Do you mean the `prusti_contracts` external crate or crates with annotations published on crates.io? The former should work even outside VSCode, while the latter case is what is not yet supported.

**Comment by fpoli** [comment] 2020-09-23 13:52
Closing as duplicate of #2

**Closed as completed by fpoli** 2020-09-23 13:52 UTC
Labels: duplicate
