### ISSUE TITLE
Panic when calling a function that returns an Option of a reference

### ISSUE THREAD

**Issue by cmatheja** [viperproject/prusti-dev#37] opened 2020-05-26 12:44 UTC
The program below causes Prusti to panic:
```rust
use prusti_contracts::*;

struct S(usize);

#[trusted]
fn foo(s: &S) -> Option<&S> { // succeeds for Option<S>
    None
}

fn bar(s: &S) {        
    let x = foo(s); // crashes
}

fn main(){}
```
The reported error message is the following:
```
thread 'main' panicked at 'assertion failed: `(left == right)`

Diff < left / right > :
<2
>1
```

**Comment by vakaras** [comment] 2020-05-26 12:48
The problem here is that referenced typed fields are not supported.

cc @alexanderjsummers

**Comment by fpoli** [comment] 2020-12-02 16:41
Prusti no longer crashes. The error message is now:
```
error: [Prusti internal error] unexpected number of type variants: 2 (should be 1)
  --> tmp/program.rs:10:1
   |
10 | / fn bar(s: &S) {        
11 | |     let x = foo(s); // crashes
12 | | }
   | |_^
```

**Comment by vakaras** [comment] 2021-03-01 13:49
Duplicate of https://github.com/viperproject/prusti-dev/issues/143

**Closed as completed by vakaras** 2021-03-01 13:49 UTC
Labels: bug, duplicate
