### ISSUE TITLE
proc macro panicked on body_invariant! with a forall

### ISSUE THREAD

**Issue by jimgrundy** [viperproject/prusti-dev#579] opened 2021-06-26 18:19 UTC
The following code panics on prusti-dev-v-2021-06-21-1121 with the following message:

```
error: proc macro panicked
  --> src/main.rs:11:9
   |
11 |         body_invariant!(result ==> (forall(|j:usize| 0 <= j && j < i ==> a[j])));
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: message: called `Option::unwrap()` on a `None` value

error: aborting due to previous error
```

```rust
use prusti_contracts::*; 

const N: usize = 5;

#[allow(dead_code)]
fn all (a:&[bool;N]) -> bool {
    let mut result = true;
    let mut i = 0;
    while i < N {
        body_invariant!(i < N);
        body_invariant!(result ==> (forall(|j:usize| 0 <= j && j < i ==> a[j])));
        result &= a[i];
        i += 1;
    }
   result
}

fn main() {
} 
```

**Comment by fpoli** [comment] 2021-06-28 13:30
Thanks for the report! However, I can't reproduce the crash using the Prusti version that you wrote. How did you run Prusti? If it's from the command line, could you rerun setting the environment variable `PRUSTI_LOG=info` and post the additional log?

**Comment by fpoli** [comment] 2021-06-28 13:52
Anyway, there is a good chance that this has already been fixed in the latest Prusti version.

**Closed as completed** 2022-08-09 14:36 UTC
Labels: to-check
