### ISSUE TITLE
Error on M1 Mac using Prusti Assistant

### ISSUE THREAD

**Issue by Gadiguibou** [viperproject/prusti-dev#1194] opened 2022-10-13 16:22 UTC
```
[stderr] dyld[31153]: Library not loaded: @rpath/libjli.dylib
  Referenced from: <29FCD4F3-7EAE-37CA-A537-334F43D07955> /Users/gabriel/Library/Application Support/Code/User/globalStorage/viper-admin.prusti-assistant/prustiTools/LatestRelease/prusti/prusti-server-driver
  Reason: tried: '/System/Volumes/Preboot/Cryptexes/OS@rpath/libjli.dylib' (no such file), '/Users/gabriel/.sdkman/candidates/java/17.0.4.1-tem/lib/libjli.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
```

Workaround:

- Install a x86_64 Java SDK and point Prusti Assistant to it using `prusti-assistant.javaHome`

**Edit**:

After installing a x86_64 Java SDK (OpenJDK 11.02), I run into the following error from `prusti-rustc` when trying to verify a crate:

```
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `/Users/gabriel/Library/Application Support/Code/User/globalStorage/viper-admin.prusti-assistant/prustiTools/LatestRelease/prusti/prusti-rustc rustc - --crate-name ___ --print=file-names --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit status: 255)
  --- stderr
  dyld[34221]: Library not loaded: @rpath/librustc_driver-88b66bfaeeb90970.dylib
    Referenced from: <0B8B796C-EA8F-3D3B-AFAB-2988B0AF6C6C> /Users/gabriel/Library/Application Support/Code/User/globalStorage/viper-admin.prusti-assistant/prustiTools/LatestRelease/prusti/prusti-driver
    Reason: tried: '/System/Volumes/Preboot/Cryptexes/OS@rpath/librustc_driver-88b66bfaeeb90970.dylib' (no such file), '/Users/gabriel/.rustup/toolchains/nightly-2022-09-18-aarch64-apple-darwin/lib/librustc_driver-88b66bfaeeb90970.dylib' (no such file), '/Users/gabriel/.rustup/toolchains/nightly-2022-09-18-aarch64-apple-darwin/bin/librustc_driver-88b66bfaeeb90970.dylib' (no such file), '/Users/gabriel/.sdkman/candidates/java/11.0.2-open/lib/jli/librustc_driver-88b66bfaeeb90970.dylib' (no such file), '/Users/gabriel/.rustup/toolchains/nightly-2022-09-18-aarch64-apple-darwin/lib/librustc_driver-88b66bfaeeb90970.dylib' (no such file), '/Users/gabriel/lib/librustc_driver-88b66bfaeeb90970.dylib' (no such file), '/usr/local/lib/librustc_driver-88b66bfaeeb90970.dylib' (no such file), '/usr/lib/librustc_driver-88b66bfaeeb90970.dylib' (no such file, not in dyld cache)
```

**Comment by Aurel300** [comment] 2022-10-13 18:42
Duplicate of #1193, please add the workaround + new error in that thread.

**Closed as completed by Aurel300** 2022-10-13 18:42 UTC
Labels: duplicate
