### ISSUE TITLE
ICE: `assertion failed: env.has_errors()`

### ISSUE THREAD

**Issue by Pointerbender** [viperproject/prusti-dev#770] opened 2021-11-21 16:44 UTC
The following rust program:

```rust
use prusti_contracts::*;

pub struct A {
    b: isize,
}

impl A {
    #[pure]
    #[ensures(result == true)]
    pub const fn invariant(&self) -> bool {
        self.is_negative() != self.is_non_negative()
    }

    #[pure]
    // #[ensures(result == (self.b >= 0))]
    pub const fn is_non_negative(&self) -> bool {
        self.b >= 0
    }

    #[pure]
    // #[ensures(result == (self.b < 0))]
    pub const fn is_negative(&self) -> bool {
        self.b < 0
    }

    #[requires(self.invariant())]
    pub const fn test(&self) {}
}

fn main() {}
```

fails with an internal compiler error and does not output any Prusti error messages. The compiler error message is `thread 'rustc' panicked at 'assertion failed: env.has_errors()', prusti/src/verifier.rs:73:17`. When uncommenting both `#[ensures(...)]` attributes, the program verifies okay and without errors.

When running Prusti with debug logging enabled, the verification errors are visible:

```
[2021-11-21T16:37:48Z DEBUG viper::verifier] Starting: Viper consistency checks
[2021-11-21T16:37:48Z DEBUG viper::verifier] Completed: Viper consistency checks (0.1 seconds)
[2021-11-21T16:37:48Z DEBUG viper::verifier] Starting: Viper verification
[2021-11-21T16:37:50Z DEBUG viper::verifier] Completed: Viper verification (1.81 seconds)
[2021-11-21T16:37:50Z DEBUG viper::verifier] Viper verification result: Verification failed with 1 errors:
      [postcondition.violated:assertion.false] Postcondition of m_invariant__$TY$__Snap$struct$m_A$$bool$ might not hold. Assertion result might not hold. (@16.5)
[2021-11-21T16:37:50Z INFO  prusti_common::stopwatch::log_level] [prusti-server] Completed: verification (1.884 seconds)
[2021-11-21T16:37:50Z DEBUG jni::wrapper::java_vm::vm] Detached thread rustc (ThreadId(2)). 0 threads remain attached
[2021-11-21T16:37:50Z INFO  prusti_common::stopwatch::log_level] [prusti-viper] Completed: verifying Viper program (17.786 seconds)
[2021-11-21T16:37:50Z DEBUG prusti_viper::verifier] Verification error in A::test: VerificationError { full_id: "postcondition.violated:assertion.false", pos_id: Some("15"), reason_pos_id: Some("15"), message: "Postcondition of m_invariant__$TY$__Snap$struct$m_A$$bool$ might not hold. Assertion result might not hold. (@16.5)", counterexample: None }
[2021-11-21T16:37:50Z DEBUG prusti_viper::encoder::errors::error_manager] Verification error: VerificationError { full_id: "postcondition.violated:assertion.false", pos_id: Some("15"), reason_pos_id: Some("15"), message: "Postcondition of m_invariant__$TY$__Snap$struct$m_A$$bool$ might not hold. Assertion result might not hold. (@16.5)", counterexample: None }
[2021-11-21T16:37:50Z DEBUG prusti_viper::verifier] Prusti error: PrustiError { is_error: true, is_disabled: true, message: "[Prusti: verification error] postcondition of pure function definition might not hold", span: MultiSpan { primary_spans: [src/lib.rs:16:5: 18:6 (#0)], span_labels: [] }, help: None, notes: [("the error originates here", Some(MultiSpan { primary_spans: [src/lib.rs:16:5: 18:6 (#0)], span_labels: [] }))] }
[2021-11-21T16:37:50Z DEBUG prusti_driver::verifier] Verifier returned Failure
thread 'rustc' panicked at 'assertion failed: env.has_errors()', prusti/src/verifier.rs:73:17
```

which seems to indicate that Prusti does detect the errors okay, but fails to emit those errors all the way to the output. Finally, Prusti terminates on this assertion when it detects that the verification has failed, but then fails to retrieve the verification errors:

https://github.com/viperproject/prusti-dev/blob/11935cadb4f94f6f5482881284730ca48176413e/prusti/src/verifier.rs#L71-L74

**Comment by vakaras** [comment] 2021-11-21 17:33
I think the problem is that the [definition collector](https://github.com/viperproject/prusti-dev/blob/master/prusti-viper/src/encoder/definition_collector.rs) does not unroll the functions deep enough.

**Comment by Pointerbender** [comment] 2021-11-22 21:17
An additional program that triggers the same internal compiler error:

```rust
use prusti_contracts::*;

pub struct A {
    entries: [usize; 4],
}

impl A {
    #[pure]
    #[requires(index < 4)]
    #[ensures(0 <= result)]
    pub fn get(&self, index: usize) -> usize {
        self.entries[index]
    }

    pub fn test(&self) {
        self.get(2);
    }
}

fn main() {}
```

The output of the debug logs reveals the underlying error:

```
[2021-11-22T20:59:27Z DEBUG prusti_viper::verifier] Verification error in A::test: VerificationError { full_id: "postcondition.violated:assertion.false", pos_id: Some("38"), reason_pos_id: Some("38"), message: "Postcondition of m_get__$TY$__Snap$struct$m_A$$int$$$int$ might not hold. Assertion 0 <= result might not hold. (@18.15)", counterexample: None }
[2021-11-22T20:59:27Z DEBUG prusti_viper::encoder::errors::error_manager] Verification error: VerificationError { full_id: "postcondition.violated:assertion.false", pos_id: Some("38"), reason_pos_id: Some("38"), message: "Postcondition of m_get__$TY$__Snap$struct$m_A$$int$$$int$ might not hold. Assertion 0 <= result might not hold. (@18.15)", counterexample: None }
[2021-11-22T20:59:27Z DEBUG prusti_viper::verifier] Prusti error: PrustiError { is_error: true, is_disabled: true, message: "[Prusti: verification error] postcondition of pure function definition might not hold", span: MultiSpan { primary_spans: [src/lib.rs:18:15: 18:26 (#0)], span_labels: [] }, help: None, notes: [("the error originates here", Some(MultiSpan { primary_spans: [src/lib.rs:18:15: 18:26 (#0)], span_labels: [] }))] }
[2021-11-22T20:59:27Z DEBUG prusti_driver::verifier] Verifier returned Failure
thread 'rustc' panicked at 'assertion failed: env.has_errors()', prusti/src/verifier.rs:73:17
```

(The underlying error `Assertion 0 <= result might not hold` also looks like a bug, since `result` is a `usize`, this assertion should always hold).

**Comment by vakaras** [comment] 2021-11-23 12:02
Thank you for reporting these bugs! The examples fail due to different reasons, but both these reasons should be fixed by the refactorings I am doing. Unfortunately, the refactorings are complicated and will take time to implement.

**Comment by Pointerbender** [comment] 2021-11-23 12:08
Thank you for working on the refactoring :) I'm just getting started on Prusti, although if there is anything I could do to help out, feel free to ping me!

**Comment by Pointerbender** [comment] 2021-12-01 08:32
For the first example in this issue, is that a another example of a corner case where the definition collector doesn't collect the specifications deep enough, or are the errors collected elsewhere? I noticed that in the debug logs the errors are present, indicating that it probably did collect the specifications, but just has trouble mapping the errors back to the specifications. I might take a stab at fixing this one over the weekend :)

**Comment by Pointerbender** [comment] 2021-12-04 16:30
I found out a bit information about the first example. For the Viper program of `A::Test`, we find the following Viper function:

```
function m_invariant__$TY$__Snap$struct$m_A$$bool$(_1: Snap$struct$m_A): Bool
  requires true
  requires true
  ensures result
  ensures [result == mirror_simple$m_invariant__$TY$__Snap$struct$m_A$$bool$(_1), true]
{
  m_is_negative__$TY$__Snap$struct$m_A$$bool$(_1) != m_is_non_negative__$TY$__Snap$struct$m_A$$bool$(_1)
}
```

`m_is_negative__$TY$__Snap$struct$m_A$$bool$` and `m_is_non_negative__$TY$__Snap$struct$m_A$$bool$` are abstract functions in this case. If we remove the `#[ensures(result == true)]` from `A::invariant`, then the program for `A::test` verifies okay and it yields the following Viper function:

```
function m_invariant__$TY$__Snap$struct$m_A$$bool$(_1: Snap$struct$m_A): Bool
  requires true
  requires true
  ensures true
  ensures [result == mirror_simple$m_invariant__$TY$__Snap$struct$m_A$$bool$(_1), true]
{
  m_is_negative__$TY$__Snap$struct$m_A$$bool$(_1) != m_is_non_negative__$TY$__Snap$struct$m_A$$bool$(_1)
}
```

`m_is_negative__$TY$__Snap$struct$m_A$$bool$` and `m_is_non_negative__$TY$__Snap$struct$m_A$$bool$` are still abstract functions in this case. The complete program that verifies is then:

```rust
use prusti_contracts::*;

pub struct A {
    b: isize,
}

impl A {
    #[pure]
    pub const fn invariant(&self) -> bool {
        self.is_negative() != self.is_non_negative()
    }

    #[pure]
    pub const fn is_non_negative(&self) -> bool {
        self.b >= 0
    }

    #[pure]
    pub const fn is_negative(&self) -> bool {
        self.b < 0
    }

    #[requires(self.invariant())]
    pub const fn test(&self) {}
}

fn main() {}
```

However, through adding the `#[ensures(result == true)]` post-condition to `A::invariant`, somehow Prusti changes the Viper postcondition `ensures true` into `ensures result` for `function m_invariant__$TY$__Snap$struct$m_A$$bool$`, causing the verification to fail (due to the missing function bodies for `m_is_negative__$TY$__Snap$struct$m_A$$bool$` and `m_is_non_negative__$TY$__Snap$struct$m_A$$bool$`).

There are now a couple questions running through my mind:

* Why/where is `ensures true` changed into `ensures result`?
* Whenever the definition collector encounters a `ensures result` post-condition, should it walk the function body in a "directly calling state"?
* If yes, would this also be required in the more general case where any post-condition depends on the `result` variable?

I'll try if I can find a couple of more examples based on the last 2 questions to help validate this line of reasoning.

**Comment by Pointerbender** [comment] 2021-12-04 16:51
An example which shows that there are more cases than just `ensures result`:

```rust
use prusti_contracts::*;

pub struct B(isize);

impl B {
    #[pure]
    #[ensures(result <= 16)]
    pub const fn get_non_negative(&self) -> isize {
        match self.get_saturated() {
            i if i < 0 => 0,
            i => i,
        }
    }

    #[pure]
    pub const fn get_saturated(&self) -> isize {
        match self.0 {
            i if i < -16 => -16,
            i if i > 16 => 16,
            i => i,
        }
    }

    #[requires(_i < self.get_non_negative())]
    pub const fn test(&self, _i: isize) {}
}

fn main() {}
```

Viper function that fails to verify due to missing dependent function bodies (`Postcondition of m_get_non_negative__$TY$__Snap$struct$m_B$$int$ might not hold. Assertion result <= 16 might not hold.`):

```
function m_get_non_negative__$TY$__Snap$struct$m_B$$int$(_1: Snap$struct$m_B): Int
  requires true
  requires true
  ensures result <= 16
  ensures -9223372036854775808 <= result
  ensures result <= 9223372036854775807
  ensures [result == mirror_simple$m_get_non_negative__$TY$__Snap$struct$m_B$$int$(_1), true]
{
  (!(m_get_saturated__$TY$__Snap$struct$m_B$$int$(_1) < 0) ? m_get_saturated__$TY$__Snap$struct$m_B$$int$(_1) : 0)
}
```

**Comment by vakaras** [comment] 2021-12-04 17:07
> For the first example in this issue, is that a another example of a corner case where the definition collector doesn't collect the specifications deep enough, or are the errors collected elsewhere?

In this case, the errors are silenced intentionally because the Viper functions should not be verified (they are verified in a different pass as Viper methods). The verification of Viper functions will be disabled once I finish my refactoring.

In a sense, the problem is the incorrect assert statement that is failing. However, I prefer to keep it for now because I hope to finish my refactoring soonish.

**Comment by vakaras** [comment] 2021-12-04 17:07
> For the first example in this issue, is that a another example of a corner case where the definition collector doesn't collect the specifications deep enough, or are the errors collected elsewhere?

In this case, the errors are silenced intentionally because the Viper functions should not be verified (they are verified in a different pass as Viper methods). The verification of Viper functions will be disabled once I finish my refactoring.

**Comment by Pointerbender** [comment] 2021-12-04 19:25
> The verification of Viper functions will be disabled once I finish my refactoring.

Ah I see. I guess this is related to [using the snap encoding of pure function in assertions](https://github.com/viperproject/prusti-dev/issues/729#issuecomment-952542847)? Does that imply that all pure Rust functions will be encoded as abstract body-less Viper functions?

I have a fix (a 4 lines change in the definition collector) that fixes the first and last example (the fix is to walk the function body in direct call mode if one of its post-conditions depends on the `__result` local variable). Shall I crate a PR for this? (meant as a temporary fix until the refactoring lands)

> However, I prefer to keep it for now

Or shall I create a PR for just the test cases and place the 2 left over examples from this issue in `verify_partial` to help test the refactoring?

Thanks!

**Comment by vakaras** [comment] 2021-12-04 19:32
> I have a fix (a 4 lines change in the definition collector) that fixes the first and last example (the fix is to walk the function body in direct call mode if one of its post-conditions depends on the `__result` local variable). Shall I crate a PR for this?

Yes, please! Just it would be good to add a comment indicating that these four lines were changed to temporarily work around this issue.

Thanks!

**Comment by Pointerbender** [comment] 2021-12-04 19:58
I just created PR #791 with the note about the temporary fix and the additional (now passing) test cases :) Thanks!

**Closed as completed** 2021-12-04 21:37 UTC
Labels: bug
