### ISSUE TITLE
Fold-unfold error when a pure function returns a non-pure value

### ISSUE THREAD

**Issue by vakaras** [viperproject/prusti-dev#683] opened 2021-09-25 14:07 UTC
Test: `prusti-tests/tests/verify/fail/issues/issue-416.rs`.

**Comment by fpoli** [comment] 2021-10-05 09:30
I would disable that test rather than making the test expect an internal error. No program in the test suite should ever expect an internal error IMO.

**Comment by vakaras** [comment] 2021-10-05 14:07
> No program in the test suite should ever expect an internal error IMO.

Not sure I agree. This corresponds to `UnexpectedOutput` errors we have in Viper and I find them useful to catch things that were “fixed by accident”. For example, things like functions taking arbitrary `Copy` arguments, which we had semi-working for 3 months until I actually noticed that.

**Comment by fpoli** [comment] 2021-10-05 14:19
Sure, but the proper error should report to the user that pure functions can only return a pure value, not an internal fold/unfold error.

**Comment by vakaras** [comment] 2021-10-05 14:41
True.

**Comment by JonasAlaif** [comment] 2022-03-21 16:55
Why is the file called `issue-416.rs` when this is 683? (i.e. can/should I rename it?)

**Comment by fpoli** [comment] 2022-03-21 17:14
The file name is correct; it's a regression test for https://github.com/viperproject/prusti-dev/issues/416.

@vakaras Do you agree that `issue-416.rs` should be supported? I have no idea what's a *non-pure* value.

Also, why don't we report "unsafe code is unsupported" errors for that test? I think we should.

Answered those questions, if the test doesn't raise an internal error anymore I think we can remove the comment about 683 and close this issue.

**Comment by vakaras** [comment] 2022-03-21 22:26
> @vakaras Do you agree that `issue-416.rs` should be supported? I have no idea what's a _non-pure_ value.

`Vec::get_unchecked` is a non-pure method, so the example should be rejected at least for that reason.

> Also, why don't we report "unsafe code is unsupported" errors for that test? I think we should.

Simply because nobody had time to add such checks.

**Comment by fpoli** [comment] 2022-03-22 12:34
> > Also, why don't we report "unsafe code is unsupported" errors for that test? I think we should.
> 
> Simply because nobody had time to add such checks.

On a second thought, I think we don't have such checks because Prusti assumes that all called functions are verified and that it's the verification of `Vec::get_unchecked` that should report the "unsafe code is unsupported" error. This is related to the default precondition `true` that we use for external functions. I opened https://github.com/viperproject/prusti-dev/issues/910 to track that, so that this issue can be closed by https://github.com/viperproject/prusti-dev/pull/895.

**Closed as completed** 2022-03-23 10:30 UTC
Labels: bug, error-reporting
