### ISSUE TITLE
Unexpected output

### ISSUE THREAD

**Issue by mabbamOG** [viperproject/prusti-dev#339] opened 2021-01-03 21:44 UTC
when checking a program with prusti-dev, i obtain the following unexpected output:

```bash
    Checking formal_test v0.1.0 (/Users/user/Downloads/TMP/formal_test)
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/user/Downloads/TMP/prusti-dev2/viper_tools/backends/ch.qos.logback.logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/user/Downloads/TMP/prusti-dev2/viper_tools/backends/silicon.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
    Finished dev [unoptimized + debuginfo] target(s) in 5.47s
```

**Comment by Aurel300** [comment] 2021-01-03 21:53
These should be harmless warnings. Duplicate of https://github.com/viperproject/viperserver/issues/26

**Closed as completed** 2021-06-15 15:31 UTC
Labels: viper-issue
